---

- name: "{{ ansible_facts['distribution'] }} - Finding files in {{ item }}."
  ansible.builtin.find:
    paths: "{{ item }}"
    hidden: true
    recurse: true
    patterns: "*"
    file_type: any
  register: files

- name: "{{ ansible_facts['distribution'] }} - Finding subdirectories in {{ item }}."
  ansible.builtin.find:
    paths: "{{ item }}"
    hidden: true
    recurse: true
    patterns: "*"
    file_type: directory
  register: directories

- name: "{{ ansible_facts['distribution'] }} - Cleaning {{ item }}."
  ansible.builtin.file:
    path: "{{ tmp_item }}"
    state: absent
  with_items: >
    {{
      files.files
      + directories.files
    }}
  loop_control:
    loop_var: tmp_item